In [256]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.datasets import load_iris
import keras
from sklearn.linear_model import LogisticRegression
from scipy.special import softmax
from copy import deepcopy

In [257]:
##### NOTE:

#No libraries imported in this file. The class relies on the following libraries, and should be imported as such:

###import numpy as np
###from sklearn.preprocessing import OneHotEncoder

#####

class logistic_regression:

    #FUNCTION to compute softmax function:
    def softmax(self,dat,weight):
        #compute product of data matrix and weights
        z = -dat@weight

        #use this to compute matrix of probabilities:
        p_matrix = (np.exp(z))/((np.exp(z).sum(axis=1)))[:,None]
        return p_matrix



    #FUNCTION to compute the gradient:
    #NOTE: mu is a hyperparamter for the l2 regularization term added to the loss function.
    #mu is a penalization term for the l2 regularization function
    def gradient(self,data,response,weights,mu):
        #get number of observations in data:
        n = np.shape(data)[0]

        #compute and return gradient:
        p = self.softmax(dat=data, weight=weights)
        grad = (((1/n)*((data.T@response) - (data.T@p)))) + ((2*mu)*weights)
        return grad



    #FUNCTION to perform basic gradient descent:
    #PURPOSE: to estimate the matrix of optimal weights needed to make predictions.
    def descent(self, data, max_iterations, y, num_classes, mu, step_size, epsilon): #HYPERPARAMETER: mu, step_size,epsilon
        #one-hot encode responses:
        encoder = OneHotEncoder(sparse=False)
        y = encoder.fit_transform(y.reshape(-1,1))

        #initialize weights:
        weights = np.zeros((np.shape(data)[1], num_classes))
        weights_new = np.zeros((np.shape(data)[1], num_classes))

        #keep track of number of iterations (for troubleshooting purposes):
        i = 0

        #loop to perform gradient descent:
        while i <= max_iterations:
            i += 1
            
            #calculate gradient:
            derivative = self.gradient(
            data=data,
            response=y,
            weights=weights,
            mu = mu
            )

            #update weights
            weights_new -= step_size*derivative
            
            #check to see if weights changed significantly or not:
            if np.linalg.norm(weights_new - weights, ord = None) < epsilon or \
            np.linalg.norm(derivative) < epsilon:
                break
            else:
                weights = deepcopy(weights_new)    
        return weights



    #FUNCTION to fit model by computing optimal weights using gradient descent:
    def fit(self,data, response, num_classes, max_iterations, mu = 0.01, step_size = 0.01, epsilon = 1e-10):
        return self.descent(data = data, y = response, max_iterations=max_iterations, num_classes = num_classes, mu=mu, step_size=step_size, epsilon = epsilon)



    #FUNCTION to make predictions:
    def predict(self,test_data,weights_from_train):
        #make predictions by multiplying test data by weights from gradient descent:
        p = self.softmax(test_data, weights_from_train)
        return np.argmax(p, axis = 1)


In [258]:
###ENSURE ROW SUMS ADD UP TO 1###
model = logistic_regression().softmax(X,weight = np.zeros((4,3)))
print(np.shape(model))
print(model)
(np.sum(model,axis = 1))

(150, 3)
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.3333

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [259]:
###LOAD THE IRIS DATASET (FOR TESTING PURPOSES)###
X = load_iris().data
Y = load_iris().target
print(np.shape(X))
print(np.shape(Y))

(150, 4)
(150,)


In [260]:
###TEST REGRESSION FUNCTION###

#fit model:
model = logistic_regression().fit(X,Y,num_classes = 3,max_iterations=1000)

#calculate correct number of predictions:
np.sum((logistic_regression().predict(X,model) == Y))

145

In [261]:
###COMPARE PERFORMANCE TO SKLEARN'S LOGISTICREGRESSION FUNCTION:###

comp_model = LogisticRegression(solver = "newton-cg").fit(X,Y)
print(comp_model.coef_)
print(np.sum(comp_model.predict(X) == Y))

[[-0.42350809  0.9673525  -2.51715173 -1.07933653]
 [ 0.53446039 -0.32158896 -0.20639209 -0.94429874]
 [-0.1109523  -0.64576355  2.72354381  2.02363527]]
146
